addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.6.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"                  % "0.14.8")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.21.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.5.11")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.3.2")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"                       % "2.3.1")
