addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin"        % "5.2.4")
addSbtPlugin("com.geirsson"            % "sbt-scalafmt"             % "1.5.1")
addSbtPlugin("ch.epfl.scala"           % "sbt-scalafix"             % "0.9.11")
addSbtPlugin("org.portable-scala"      % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"            % "sbt-scalajs"              % "1.1.0")
addSbtPlugin("com.jsuereth"            % "sbt-pgp"                  % "2.0.1")
